# Generated by Django 2.2.2 on 2019-06-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='is_email_public',
            field=models.BooleanField(default=False),
        ),
    ]
