# Generated by Django 2.1.3 on 2018-11-06 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import permissions.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('invited_user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('objects', permissions.models.ProjectManager()),
            ],
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='project',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='permissions.Project'),
        ),
    ]
