# Generated by Django 2.1.3 on 2018-11-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20181106_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinvitation',
            old_name='invited_user',
            new_name='owner',
        ),
    ]
