# Generated by Django 2.1.3 on 2018-11-07 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_auto_20181106_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='projectList', to=settings.AUTH_USER_MODEL),
        ),
    ]
