# Generated by Django 2.2.2 on 2019-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0002_auto_20190613_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(upload_to='Narrow/cdn_data//images/profile_images'),
        ),
    ]
