# Generated by Django 2.2.2 on 2019-06-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_auto_20190613_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
