# Generated by Django 2.1.3 on 2019-06-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppermission',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='owner',
        ),
        migrations.DeleteModel(
            name='GroupPermission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
