# Generated by Django 2.2.2 on 2019-06-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190611_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
