# Generated by Django 2.2.2 on 2020-05-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectinvitation_is_rejected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
