# Generated by Django 2.2.2 on 2019-06-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190614_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskpart',
            name='partent',
        ),
        migrations.AddField(
            model_name='taskpart',
            name='parent',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='tasks.Task'),
            preserve_default=False,
        ),
    ]
