# Generated by Django 2.2.2 on 2019-06-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190614_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskPart',
            new_name='SubTask',
        ),
    ]
