# Generated by Django 2.2.2 on 2019-06-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20190619_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='deadline',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
