# Generated by Django 2.2.2 on 2020-05-21 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_subtask_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('READ', 'Read'), ('EDIT', 'Edit')], default='READ', max_length=4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskPermission', to='tasks.Task')),
            ],
        ),
    ]
