# Generated by Django 2.2.2 on 2019-06-13 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cdn_data/pictures/profile_pictures')),
                ('url', models.TextField(max_length=5000)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilePicture', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
