# Generated by Django 2.2.2 on 2019-06-20 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_subtask_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdn', '0003_auto_20190614_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Narrow/cdn_data//images/task_file/')),
                ('url', models.TextField(max_length=5000)),
                ('name', models.TextField(max_length=5000)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uploadedSubTaskFiles', to=settings.AUTH_USER_MODEL)),
                ('sub_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subTaskFiles', to='tasks.SubTask')),
            ],
        ),
    ]
